### ISSUE TITLE
Add Caucasian Squirrel

### ISSUE THREAD

**Issue by mertturkmenoglu** [tutkuofnight/sincapwiki#1]
Hi,

Please consider adding Caucasian Squirrel (Sciurus anomalus)

https://en.wikipedia.org/wiki/Caucasian_squirrel

![image](https://github.com/user-attachments/assets/5d9ea6a1-e507-4dcc-bba5-1dfee386bc86)

**Comment by tutkuofnight** [comment]
Sure, i will add this content asap. Thanks 💯
